project:
  type: website
  output-dir: docs

website:
  title: "Selenia Anastasi"
  navbar:               # <--- Deve avere lo stesso rientro di 'title'
    background: dark
    left:
      - href: index.qmd
        text: Home
        href: pagina2.qmd
        text: Projects
      - href: pubblicazioni.qmd
        text: Publications
      - href: conferences.qmd
        text: Conferences
      - href: contatti.qmd
        text: Find me

format:
  html:
    theme: cosmo
    external-link-target: "_blank"